package sec.filesystem;

import java.util.logging.Level;
import java.util.logging.Logger;

/*  Demo Class used for demonstrating a client connecting to the File Server, 
    with an expired certificate. 
    A smartcard with expired certificates in required in order to run this test.

    Please refer to the output generated by the server at runtime as it
    receives and processes the Demo Apps requests, for information on the 
    exceptions caught by the file system, and the returns of the operations 
    being performed by the server.

    WARNING
    This demo App currently only works if using smartcards.
 */
public class DemoExpiredCertificate {

    public static void main(String[] args) {
        try {
            Library c = new Library();
            
            // Initializing the file system
            System.out.println("Initializing the File System...");
            c.setClientID(c.fs_init());
            System.out.println("Done!");
            System.out.println("Client ID assigned by server: " + c.getClientID().getValue());
            System.out.println("---------------------------------------------------------\n");
            
        } catch (Exception ex) {
            System.out.println("[Catch] Exception: " + ex.getMessage());
            Logger.getLogger(DemoExpiredCertificate.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
